In [ ]:
import numpy as np

# Scalars

# Vectors

In [43]:

v = np.array([[9],[10],[11]])

print("0th element of v:", v[0])
print("2nd element of v:", v[2])

0th element of v: [9]
2nd element of v: [11]


# Matrics

In [14]:
x = np.array([[1,2],[3,4]])

print("0,0 element of x:", x[0][0])
print("1,1 element of x:", x[1][1])

[[1 2]
 [3 4]]
0,0 element of x: 1
1,1 element of x: 4


In [22]:
print(np.mat(x))

[[1 2]
 [3 4]]


# Tensors

In [11]:
y = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ],
        [
            [11, 12, 13],
            [14, 15, 16],
            [17, 18, 19]
        ]
    ]
)
print(y[0][0][0])
print(y[1][0][2])

1
13


# Transpose

In [13]:
x_t = np.transpose(x)

print("Matrix")
print(x)
print("transposed Matrix")
print(x_t)

[[1 3]
 [2 4]]


In [16]:
y = np.array([[1,2],[3,4],[5,6]])
y_t = np.transpose(y)


print("Matrix")
print(y)
print("transposed Matrix")
print(y_t)

print("transposed elements")
print(y[2][0])
print(y_t[0][2])

Matrix
[[1 2]
 [3 4]
 [5 6]]
transposed Matrix
[[1 3 5]
 [2 4 6]]
5
5


# Matrix operations

In [19]:
print(x)
x_2 = 2*x + 3
print(x_2)

[[1 2]
 [3 4]]
[[ 5  7]
 [ 9 11]]


In [20]:
print(x+x_2)
print(x*x_2)

[[ 6  9]
 [12 15]]
[[ 5 14]
 [27 44]]


In [21]:
print(np.dot(x, x_2))

[[23 29]
 [51 65]]


In [23]:
print(np.mat(x) * np.mat(x_2))

[[23 29]
 [51 65]]


# Matrix Associativity, Distributivity, Commutative

In [31]:
x_10 = np.array([[1, 2], [3, 4]])
x_11 = np.array([[5, 6], [7, 8]])
x_12 = np.array([[9, 10], [11, 12]])

In [32]:
print("Distributive")
print(x_10*(x_11+x_12))
print(x_10*x_11 + x_10*x_12)

print("Associative")
print(x_10*(x_11*x_12))
print((x_10*x_11)*x_12)

print("Commutative")
print(x_10*x_11)
print(x_11*x_10)

Distributive
[[14 32]
 [54 80]]
[[14 32]
 [54 80]]
Associative
[[ 45 120]
 [231 384]]
[[ 45 120]
 [231 384]]
Commutative
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [36]:
print("Distributive")
print(np.dot(x_10, (x_11+x_12)))
print(np.dot(x_10, x_11) + np.dot(x_10, x_12))

print("Associative")
print(np.dot(x_10, np.dot(x_11, x_12)))
print(np.dot(np.dot(x_10, x_11), x_12))

print("Not Commutative!")
print(np.dot(x_10, x_11))
print(np.dot(x_11, x_10))

Distributive
[[ 50  56]
 [114 128]]
[[ 50  56]
 [114 128]]
Associative
[[ 413  454]
 [ 937 1030]]
[[ 413  454]
 [ 937 1030]]
Not Commutative!
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [38]:
print(np.transpose(x_10*x_11))
print(np.transpose(x_10)*np.transpose(x_11))
print(np.transpose(np.dot(x_10, x_11)))
print(np.dot(np.transpose(x_11), np.transpose(x_10)))

[[ 5 21]
 [12 32]]
[[ 5 21]
 [12 32]]
[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


# Linear equation as Matrix-Vector-Multiplication

In [44]:
x_20 = np.array(
[[1, 2], 
 [3, 4], 
 [5, 6]])
v_20 = np.array([[1],[2],[3]])

print(x_20 * v_20)
print(np.dot(x_20, v_20))

[[ 1  2]
 [ 6  8]
 [15 18]]


ValueError: shapes (3,2) and (3,1) not aligned: 2 (dim 1) != 3 (dim 0)

# Identity Matrix

In [46]:
x_i = np.identity(2)
print(x_i)

[[ 1.  0.]
 [ 0.  1.]]


# Diagonal Matrix

In [50]:
x_d = np.diag([1, 2, 3])
print(x_d)
print(np.transpose(x_d))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
